version: '3.4'
services:
  weaviate:
    image: weaviate/debug-server
    build:
      context: .
      dockerfile: debug.Dockerfile
      target: weaviate_debug
    restart: on-failure:0
    ports:
      - "2345:2345"
      - "8080:8080"
      - "6060:6060"
      - "2112:2112"
      - "7101:7101"
      - "50051:50051"
    environment:
      LOG_LEVEL: "debug"
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: text2vec-contextionary
      ENABLE_MODULES: text2vec-contextionary
      PROMETHEUS_MONITORING_ENABLED: 'true'
      PROMETHEUS_MONITORING_GROUP_CLASSES: 'true'
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_DATA_BIND_PORT: "7101"
      ASYNC_INDEXING: ${ASYNC_INDEXING:-false}
      PERSISTENCE_MEMTABLES_FLUSH_DIRTY_AFTER_SECONDS: 2

      # Proxy settings
      HTTP_PROXY: "http://simi:JadeMoyo100%@172.16.0.171:8080"
      HTTPS_PROXY: "http://simi:JadeMoyo100%@172.16.0.171:8080"
      NO_PROXY: "localhost,127.0.0.1"
    
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    ports:
      - "9999:9999"
    environment:


